#!/data/data/com.termux/files/usr/bin/bash

SYSBIN=/system/bin
SYSXBIN=/system/xbin
PRE=/data/data/com.termux/files
ROOT_HOME=$PRE/home/root
BINPRE=$PRE/usr/bin
LDLP="export LD_LIBRARY_PATH=$PRE/usr/lib"
CMDLINE="PATH=$PATH:$SYSXBIN:$SYSBIN;$LDLP;HOME=$ROOT_HOME;cd $PWD"

if [ -x $SYSXBIN/su ]; then
	SU=$SYSXBIN/su
elif [ -x /su/bin/su ]; then
	SU=/su/bin/su
elif [ -x /sbin/su ]; then
	SU=/sbin/su
else
	echo "\nsu executable not found"
	echo "sudo requires su\n"
	exit
fi

if [ ! -d $ROOT_HOME ]; then
	$SU -c "mkdir $ROOT_HOME"
	$SU -c "chmod 700 $ROOT_HOME"
fi

ARGS=$(printf '%q ' "$@")

CMDLINE="$CMDLINE;$BINPRE/zsh"

pre_env_chk=`$SU --help|grep -e --preserve-environment`
if [ -n "$pre_env_chk" ]; then
        $SU --preserve-environment -c "$CMDLINE"
else
        $SU -c "$CMDLINE"
fi

